---

- name: Include OS-dependent variables
  include_vars:
    file: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_major_version }}.yml"
      - "{{ ansible_facts.distribution }}.yml"
      - "{{ ansible_facts.os_family }}_{{ ansible_facts.distribution_major_version }}.yml"
      - "{{ ansible_facts.os_family }}.yml"
      skip: true
  tags: always

- name: Include OS-dependent tasks
  include_tasks:
    file: "{{ item }}"
  with_first_found:
    - files:
      - "os/{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_major_version }}.yml"
      - "os/{{ ansible_facts.distribution }}.yml"
      - "os/{{ ansible_facts.os_family }}_{{ ansible_facts.distribution_major_version }}.yml"
      - "os/{{ ansible_facts.os_family }}.yml"
      skip: true
  tags: always

# Install PHP
- name: Download PHP
  become: yes
  action: >
    {{ ansible_pkg_mgr }} name={{ php_packages | mandatory }} state=present update_cache=yes

- name: Start PHP-FPM service
  become: yes
  service:
    name: "{{ php_service_name | mandatory }}"
    enabled: true
    state: started

# copy php-fpm.conf to apache configuration directory
# - name: Enable PHP-FPM in apache2
#   become: yes
#   command: a2enconf php{{ php_version | mandatory }}-fpm
#   notify:
#     - restart apache
#   when: ansible_facts.os_family == "Debian"

# php config.
- name: Update php.ini
  become: yes
  lineinfile:
    dest: "{{ php_ini }}"
    create: yes
    line: "{{ item.key }} = {{ item.value }}"
  with_dict: "{{ vccw.php_ini }}"
  notify:
    - restart apache

- name: Update php.ini for cli
  become: yes
  lineinfile:
    dest: "{{ php_ini_cli }}"
    create: yes
    line: "{{ item.key }} = {{ item.value }}"
  with_dict: "{{ vccw.php_ini }}"
  when: php_ini != php_ini_cli

- name: "Updating Apache User with PHP-FPM"
  become: yes
  lineinfile:
    dest: "{{ php_fpm_conf }}"
    backrefs: yes
    regexp: '^(;\s*)?listen\.owner\s*='
    line: 'listen.owner = {{ apache_user }}'
  notify:
    - restart php-fpm

- name: "Updating Apache Group with PHP-FPM"
  become: yes
  lineinfile:
    dest: "{{ php_fpm_conf }}"
    backrefs: yes
    regexp: '^(;\s*)?listen\.group\s*='
    line: 'listen.group = {{ apache_user }}'
  notify:
    - restart php-fpm

- import_tasks: composer.yml
