---

apache_service_name: apache2

apache_packages:
- apache2
- libapache2-mod-fcgid

apache_config: /etc/apache2/apache2.conf

apache_configs_dir: /etc/apache2/conf-enabled

apache_site_conf_path: /etc/apache2/sites-available

apache_modules_path: /usr/lib/apache2/modules

apache_modules_conf_path: /etc/apache2/mods-enabled
