---

# Install mailcatcher as root
- name: Install mailcatcher
  become: yes
  gem:
    name: mailcatcher
    state: latest
    user_install: no
  when: vccw.mailcatcher

- name: Add mailcatcher to service
  become: yes
  template:
    src: templates/mailcatcher.service
    dest: /etc/systemd/system/mailcatcher.service
    mode: 0644
  when: vccw.mailcatcher

- name: Start mailcatcher
  become: yes
  service:
    name: mailcatcher
    enabled: yes
    state: started
  when: vccw.mailcatcher

- name: Update php.ini for mailcatcher
  become: yes
  lineinfile:
    dest: "{{ php_ini }}"
    create: yes
    line: "sendmail_path = /usr/bin/env catchmail"
  when: vccw.mailcatcher
  notify:
    - restart apache

- name: Update php.ini for mailcatcher for cli
  become: yes
  lineinfile:
    dest: "{{ php_ini_cli }}"
    create: yes
    line: "sendmail_path = /usr/bin/env catchmail"
  when: vccw.mailcatcher && php_ini != php_ini_cli
