---

- name: wp-cli-config
  template:
    src: templates/guest-wp-cli-config.yml
    dest: "{{ ansible_env.HOME }}/.wp-cli/config.yml"

- name: wp-cli-local-config
  template:
    src: templates/wp-cli.yml
    dest: "{{ vccw.vagrant_dir }}/wp-cli.yml"
    force: no
